services:
  # MailHog - Email testing tool
  mailhog:
    image: mailhog/mailhog:latest
    container_name: panel1-mailhog
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI
    environment:
      - MH_STORAGE=memory
      - MH_UI_BIND_ADDR=0.0.0.0:8025
      - MH_API_BIND_ADDR=0.0.0.0:8025
      - MH_SMTP_BIND_ADDR=0.0.0.0:1025
    networks:
      - panel1-network

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: panel1-postgres
    environment:
      POSTGRES_DB: panel1_dev
      POSTGRES_USER: panel1_user
      POSTGRES_PASSWORD: panel1_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - panel1-network

  # Redis for job queues
  redis:
    image: redis:7-alpine
    container_name: panel1-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - panel1-network

volumes:
  postgres_data:
  redis_data:

networks:
  panel1-network:
    driver: bridge 